module.exports = {
	env: {
		browser: true,
		commonjs: true,
		es6: true,
		node: true,
		mocha: true
	},
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2018,
		ecmaFeatures: {
			impliedStrict: true
		}
	},
	rules: {
		'constructor-super': 2,
		'for-direction': 2,
		'no-async-promise-executor': 2,
		'no-case-declarations': 2,
		'no-class-assign': 2,
		'no-compare-neg-zero': 2,
		'no-cond-assign': 2,
		'no-const-assign': 2,
		'no-constant-condition': 2,
		'no-control-regex': 2,
		'no-debugger': 2,
		'no-delete-var': 2,
		'no-dupe-args': 2,
		'no-dupe-class-members': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-empty': 2,
		'no-empty-character-class': 2,
		'no-empty-pattern': 2,
		'no-ex-assign': 2,
		'no-extra-boolean-cast': 2,
		'no-extra-semi': 2,
		'no-fallthrough': 2,
		'no-func-assign': 2,
		'no-global-assign': 2,
		'no-inner-declarations': 2,
		'no-invalid-regexp': 2,
		'no-irregular-whitespace': 2,
		'no-misleading-character-class': 2,
		'no-mixed-spaces-and-tabs': 2,
		'no-new-symbol': 2,
		'no-obj-calls': 2,
		'no-octal': 2,
		'no-prototype-builtins': 2,
		'no-redeclare': 2,
		'no-regex-spaces': 2,
		'no-self-assign': 2,
		'no-shadow-restricted-names': 2,
		'no-sparse-arrays': 2,
		'no-this-before-super': 2,
		'no-undef': 2,
		'no-unexpected-multiline': 2,
		'no-unreachable': 2,
		'no-unsafe-finally': 2,
		'no-unsafe-negation': 2,
		'no-unused-labels': 2,
		'no-unused-vars': 2,
		'no-useless-catch': 2,
		'no-useless-escape': 2,
		'require-atomic-updates': 2,
		'require-yield': 2,
		'use-isnan': 2,
		'valid-typeof': 2,
		indent: [ 2, 'tab' ],
		'linebreak-style': [ 2, 'unix' ],
		quotes: [ 2, 'single' ],
		semi: [ 2, 'always' ],
		curly: 2,
		'brace-style': [ 2, '1tbs' ],
		camelcase: [ 2, {
			properties: 'always'
		} ],
		'comma-spacing': [ 2, {
			before: false,
			after: true
		} ],
		'comma-style': [ 2, 'last' ],
		'comma-dangle': [ 2, 'never' ],
		'key-spacing': [ 2, {
			mode: 'strict',
			beforeColon: false,
			afterColon: true
		} ],
		'keyword-spacing': 2,
		'block-spacing': 2,
		'array-bracket-spacing': [ 2, 'always' ],
		'object-curly-spacing': [ 2, 'always' ],
		'computed-property-spacing': [ 2, 'always' ],
		'space-in-parens': [ 2, 'always' ],
		'space-before-function-paren': [ 2, 'never' ],
		'generator-star-spacing': [ 2, 'after' ],
		'yield-star-spacing': [ 2, 'after' ],
		'space-infix-ops': 2,
		'space-unary-ops': 2,
		'spaced-comment': [ 2, 'always' ],
		'arrow-spacing': [ 2, {
			before: true,
			after: true
		} ],
		'arrow-parens': [ 2, 'always' ],
		'arrow-body-style': [ 2, 'always' ],
		'no-trailing-spaces': 2,
		'no-multiple-empty-lines': [ 2, {
			max: 1
		} ],
		'eol-last': 2,
		'valid-jsdoc': 2,
		'no-implicit-coercion': [ 2, {
			allow: [ '!!' ]
		} ],
		'no-native-reassign': 2,
		'no-extend-native': 2,
		'wrap-iife': [ 2, 'outside' ],
		'yoda': [ 2, 'never' ],
		'prefer-arrow-callback': 2,
		'prefer-const': 2,
		'no-var': 2,
		'prefer-template': 2,
		'prefer-rest-params': 2,
		'prefer-spread': 2,
		'object-shorthand': [ 2, 'always' ],
		'no-array-constructor': 2,
		'no-new-object': 2,
		'new-cap': 2,
		'new-parens': 2,
		'no-lonely-if': 2,
		'no-use-before-define': 2,
		'no-with': 2,
		'eqeqeq': [ 2, 'smart' ],
		'getter-return': [ 2, {
			allowImplicit: true
		} ],
		'no-await-in-loop': 2,
		'dot-location': [ 2, 'object' ],
		'dot-notation': 2,
		'array-callback-return': 2,
		'no-proto': 2,
		'no-return-await': 2,
		'func-style': [ 2, 'declaration', {
			allowArrowFunctions: true
		} ],
		'require-await': 2
	}
};
